services:
  django:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["python", "-m", "daphne", "-b", "0.0.0.0", "-p", "80", "asgi:application"]
    depends_on:
      - "redis"
    volumes:
      - ./project:/project
      - ./data:/data
    ports:
      - "80:80"
  background:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["django-admin", "runworker", "background"]
    depends_on:
      - "redis"
    volumes:
      - ./project:/project
      - ./data:/data
  redis:
    image: docker.io/redis:latest
    command: redis-server --save 60 1 --loglevel warning
