services:
  django:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["uvicorn", "asgi:application", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./project:/project
      - ./data:/data
    ports:
      - "8800:8000"
  ingest:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["python", "manage.py", "ingest"]
    restart: always
    volumes:
      - ./project:/project
      - ./data:/data
