services:
  django:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["python", "-m", "gunicorn", "asgi:application", "--bind=0.0.0.0:80", "--forwarded-allow-ips", "*", "--log-level=info", "--reload", "-k", "uvicorn.workers.UvicornWorker"]
    volumes:
      - ./project:/project
      - ./data:/data
    ports:
      - "80:80"
  ingest:
    environment:
      DJANGO_SETTINGS_MODULE: "settings"
    build: .
    command: ["python", "manage.py", "ingest"]
    restart: always
    volumes:
      - ./project:/project
      - ./data:/data
