# Generated by Django 5.1 on 2024-08-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mw_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevertRiskLaResponse",
            fields=[
                ("model_version", models.PositiveSmallIntegerField(null=True)),
                (
                    "revision_create",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="mw_events.revisioncreate",
                    ),
                ),
                ("prediction", models.BooleanField(null=True)),
                (
                    "true_probability",
                    models.DecimalField(decimal_places=17, max_digits=17, null=True),
                ),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("error_detail", models.CharField(max_length=256, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("requested", models.DateTimeField()),
                ("model_name", models.CharField(max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RevertRiskMlResponse",
            fields=[
                ("model_version", models.PositiveSmallIntegerField(null=True)),
                (
                    "revision_create",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="mw_events.revisioncreate",
                    ),
                ),
                ("prediction", models.BooleanField(null=True)),
                (
                    "true_probability",
                    models.DecimalField(decimal_places=17, max_digits=17, null=True),
                ),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("error_detail", models.CharField(max_length=256, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("requested", models.DateTimeField()),
                ("model_name", models.CharField(max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
