# Generated by Django 5.1 on 2024-08-26 03:12

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mw_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiftwingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.PositiveSmallIntegerField(null=True)),
                ("model_name", models.CharField(max_length=128, null=True)),
                ("prediction", models.BooleanField(null=True)),
                (
                    "true_probability",
                    models.DecimalField(decimal_places=17, max_digits=17, null=True),
                ),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("error_detail", models.CharField(max_length=256, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("requested", models.DateTimeField()),
                (
                    "elapsed",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("created"), "-", models.F("requested")
                        ),
                        output_field=models.DurationField(),
                    ),
                ),
                (
                    "revision_create",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liftwingresponse",
                        to="mw_events.revisioncreate",
                    ),
                ),
            ],
        ),
    ]
