# Generated by Django 5.1 on 2024-08-29 19:22

from django.db import migrations, models


def fill_dt_rev_id(apps, schema):
    LiftwingResponse = apps.get_model("mw_scores", "LiftwingResponse")
    for score in LiftwingResponse.objects.all():
        score.dt = score.revision_create.dt
        score.rev_id = score.revision_create.rev_id
        score.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mw_scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liftwingresponse",
            name="dt",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="liftwingresponse",
            name="rev_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.RunPython(fill_dt_rev_id),
    ]
