# Generated by Django 5.1 on 2024-08-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mw_events", "0001_initial"),
        ("mw_scores", "0002_liftwingresponse_dt_liftwingresponse_rev_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="liftwingresponse",
            index=models.Index(fields=["rev_id"], name="mw_scores_l_rev_id_cefd52_idx"),
        ),
        migrations.AddIndex(
            model_name="liftwingresponse",
            index=models.Index(fields=["dt"], name="mw_scores_l_dt_584ac2_idx"),
        ),
        migrations.AddIndex(
            model_name="liftwingresponse",
            index=models.Index(
                fields=["model_name"], name="mw_scores_l_model_n_e687a1_idx"
            ),
        ),
    ]
