# Generated by Django 5.1 on 2024-08-22 03:32

import mw_events.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RevisionCreate",
            fields=[
                ("schema", models.CharField(max_length=128)),
                ("comment", models.CharField(max_length=128, null=True)),
                ("database", models.CharField(max_length=32)),
                ("dt", models.DateTimeField()),
                ("meta", models.JSONField()),
                ("page_id", models.PositiveBigIntegerField()),
                ("page_is_redirect", models.BooleanField()),
                ("page_namespace", models.PositiveIntegerField()),
                ("page_title", models.CharField(max_length=128)),
                ("performer", models.JSONField()),
                ("rev_content_changed", models.BooleanField(default=False)),
                ("rev_content_format", models.CharField(max_length=128, null=True)),
                ("rev_content_model", models.CharField(max_length=128, null=True)),
                (
                    "rev_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("rev_is_revert", models.BooleanField(default=False)),
                ("rev_len", models.BigIntegerField(null=True)),
                ("rev_minor_edit", models.BooleanField(default=False)),
                ("rev_parent_id", models.PositiveBigIntegerField(null=True)),
                (
                    "rev_revert_details",
                    models.JSONField(
                        default=mw_events.models.RevisionCreate.json_default
                    ),
                ),
                ("rev_sha1", models.CharField(max_length=128, null=True)),
                (
                    "rev_slots",
                    models.JSONField(
                        default=mw_events.models.RevisionCreate.json_default
                    ),
                ),
                ("rev_timestamp", models.DateTimeField()),
            ],
            options={
                "get_latest_by": "dt",
                "indexes": [
                    models.Index(fields=["dt"], name="mw_events_r_dt_defa5e_idx")
                ],
            },
        ),
    ]
